[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16.x" # or any version you want to use

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
