[build]
  publish = "frontend/build"  
  command = "npm install && npm run build" 

[dev]
  command = "npm start" 
  port = 3000
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
